/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model (props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/glb/lowpolydude.gltf')

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      Tpose: mixer.clipAction(animations[0], group.current),
      idle: mixer.clipAction(animations[1], group.current),
      jump: mixer.clipAction(animations[2], group.current),
      pickup: mixer.clipAction(animations[3], group.current),
      run: mixer.clipAction(animations[4], group.current)
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          material={nodes.Group2.material}
          geometry={nodes.Group2.geometry}
          skeleton={nodes.Group2.skeleton}
        />
        <skinnedMesh
          material={nodes.Group3.material}
          geometry={nodes.Group3.geometry}
          skeleton={nodes.Group3.skeleton}
        />
        <skinnedMesh
          material={nodes.Group4.material}
          geometry={nodes.Group4.geometry}
          skeleton={nodes.Group4.skeleton}
        />
        <skinnedMesh
          material={nodes.Group6.material}
          geometry={nodes.Group6.geometry}
          skeleton={nodes.Group6.skeleton}
        />
        <skinnedMesh
          material={nodes.Group7.material}
          geometry={nodes.Group7.geometry}
          skeleton={nodes.Group7.skeleton}
        />
        <skinnedMesh
          material={materials['Material.001']}
          geometry={nodes.Group1.geometry}
          skeleton={nodes.Group1.skeleton}
        />
        <skinnedMesh
          material={materials['Material.004']}
          geometry={nodes.Group10.geometry}
          skeleton={nodes.Group10.skeleton}
        />
        <skinnedMesh
          material={materials['Material.003']}
          geometry={nodes.Group11.geometry}
          skeleton={nodes.Group11.skeleton}
        />
        <skinnedMesh
          material={materials['Material.002']}
          geometry={nodes.Group12.geometry}
          skeleton={nodes.Group12.skeleton}
        />
        <skinnedMesh
          material={materials['Material.007']}
          geometry={nodes.Group5.geometry}
          skeleton={nodes.Group5.skeleton}
        />
        <skinnedMesh
          material={materials['Material.006']}
          geometry={nodes.Group8.geometry}
          skeleton={nodes.Group8.skeleton}
        />
        <skinnedMesh
          material={materials['Material.005']}
          geometry={nodes.Group9.geometry}
          skeleton={nodes.Group9.skeleton}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[1.09, -1.5, -49]} rotation={[-1.68, -0.75, -0.07]}>
          <group position={[0, 6.36, -0.7]} rotation={[-0.01, 0.08, -0.01]}>
            <group position={[0, 7.47, 0]} rotation={[0.21, 0.16, -0.04]}>
              <group position={[0, 8.53, 0]} rotation={[0.21, 0.16, -0.04]} scale={[1, 1, 1]}>
                <group position={[0, 9.6, 0]} rotation={[0.04, -0.02, 0]}>
                  <group position={[0, 11.12, 1.62]} rotation={[-0.11, 0.36, -0.01]} />
                </group>
                <group position={[4.68, 7.84, -0.19]} rotation={[1.59, -0.35, -1.6]} scale={[1, 1, 1]}>
                  <group position={[0, 9.88, 0]} rotation={[0.92, -0.2, 0.11]}>
                    <group position={[0, 12.7, 0]} rotation={[0.01, 0.14, 0.83]}>
                      <group position={[0, 16.55, 0]} rotation={[-0.38, 0.48, 0.13]}>
                        <group position={[-2.45, 1.96, 0]} rotation={[0.46, 0.39, 0.38]}>
                          <group position={[-0.05, 2.51, 0]} rotation={[-0.01, -0.01, -0.13]}>
                            <group position={[-0.56, 3.91, 0]} rotation={[0, 0, 0.33]} />
                          </group>
                        </group>
                        <group position={[0, 4.76, 0.05]} rotation={[0.06, -0.02, 0.14]} scale={[1, 1, 1]}>
                          <group position={[0.03, 3.94, 0]} rotation={[0.29, 0, 0.01]} scale={[1, 1, 1]}>
                            <group position={[-0.01, 3.5, 0]} rotation={[0, 0, -0.01]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-4.68, 7.85, -0.2]} rotation={[1.65, 0.39, 1.44]}>
                  <group position={[0, 9.88, 0]} rotation={[0.73, 0.39, 0.34]}>
                    <group position={[0, 12.7, 0]} rotation={[0.18, -0.02, -0.72]}>
                      <group position={[0, 16.57, 0]} rotation={[0.14, -0.42, -0.19]}>
                        <group position={[2.28, 2.18, 0]} rotation={[0.33, -0.08, -0.51]}>
                          <group position={[0.04, 2.52, 0]} rotation={[0.09, 0.02, 0.48]}>
                            <group position={[0.57, 3.95, 0]} rotation={[0, 0, -0.34]} />
                          </group>
                        </group>
                        <group position={[0, 4.68, 0.16]} rotation={[0.12, 0, 0.02]}>
                          <group position={[0.05, 3.63, 0]} rotation={[0.29, 0, -0.09]}>
                            <group position={[-0.15, 4.13, 0]} rotation={[0, 0, 0.08]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[6.38, -3.54, 1.07]} rotation={[-0.52, 0.1, -2.89]} scale={[1, 1, 1]}>
            <group position={[0, 23.9, 0]} rotation={[-0.78, 0.25, 0.02]}>
              <group position={[0, 21.07, 0]} rotation={[1.26, 0.05, -0.18]}>
                <group position={[0, 10.69, 0]} rotation={[0.74, 0.27, -0.26]} />
              </group>
            </group>
          </group>
          <group position={[-6.38, -3.54, 1.36]} rotation={[-0.09, -0.24, 2.86]} scale={[1, 1, 1]}>
            <group position={[0, 23.85, 0]} rotation={[-0.75, 0.14, 0]}>
              <group position={[0, 21.07, 0]} rotation={[1.59, 0.17, 0.2]} scale={[1, 1, 1]}>
                <group position={[0, 11.1, 0]} rotation={[0.69, -0.27, 0.2]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[-0.53, -1.84, -44.37]} rotation={[-1.21, 0.31, 0.05]}>
          <group position={[0, 6.36, -0.7]} rotation={[0.15, -0.2, -0.03]}>
            <group position={[0, 7.47, 0]} rotation={[0.02, -0.05, -0.02]}>
              <group position={[0, 8.53, 0]} rotation={[0.02, -0.05, -0.02]} scale={[1, 1, 1]}>
                <group position={[0, 9.6, 0]} rotation={[-0.02, 0.03, -0.02]}>
                  <group position={[0, 11.12, 1.62]} rotation={[-0.43, -0.08, 0.07]} />
                </group>
                <group position={[4.68, 7.84, -0.19]} rotation={[1.65, -0.55, -1.43]} scale={[1, 1, 1]}>
                  <group position={[0, 9.88, 0]} rotation={[0.54, -0.14, 0.48]}>
                    <group position={[0, 12.7, 0]} rotation={[0.11, 0.14, 1.76]} scale={[1, 1, 1]}>
                      <group position={[0, 16.55, 0]} rotation={[-0.33, 0.76, 0.38]}>
                        <group position={[-2.45, 1.96, 0]} rotation={[0.29, 0.11, 0.56]}>
                          <group position={[-0.05, 2.51, 0]} rotation={[0.24, 0.02, -0.55]}>
                            <group position={[-0.56, 3.91, 0]} rotation={[-0.29, -0.12, 0.77]} />
                          </group>
                        </group>
                        <group position={[0, 4.76, 0.05]} rotation={[1.08, -0.03, 0.14]}>
                          <group position={[0.03, 3.94, 0]} rotation={[1.06, -0.01, -0.01]} scale={[1, 1, 1]}>
                            <group position={[-0.01, 3.5, 0]} rotation={[0.61, 0, -0.01]} scale={[1, 1, 1]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-4.68, 7.85, -0.2]} rotation={[1.54, 0.42, 1.68]}>
                  <group position={[0, 9.88, 0]} rotation={[0.81, -0.07, 0.86]}>
                    <group position={[0, 12.7, 0]} rotation={[0.1, -0.08, -1.14]}>
                      <group position={[0, 16.57, 0]} rotation={[-0.46, -0.48, -0.36]}>
                        <group position={[2.28, 2.18, 0]} rotation={[-0.04, -0.13, -0.61]}>
                          <group position={[0.04, 2.52, 0]} rotation={[0.33, 0.22, 0.52]} scale={[1, 1, 1]}>
                            <group position={[0.57, 3.95, 0]} rotation={[-0.47, -0.08, -0.57]} />
                          </group>
                        </group>
                        <group position={[0, 4.68, 0.16]} rotation={[0.47, -0.06, -0.27]}>
                          <group position={[0.05, 3.63, 0]} rotation={[1.37, -0.1, -0.15]}>
                            <group position={[-0.15, 4.13, 0]} rotation={[0.53, 0, 0.01]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[6.38, -3.54, 1.07]} rotation={[-0.51, 0, 3.09]}>
            <group position={[0, 23.9, 0]} rotation={[-1.15, 0.12, 0.09]}>
              <group position={[0, 21.07, 0]} rotation={[1.89, 0.1, -0.14]}>
                <group position={[0, 10.69, 0]} rotation={[0.87, 0.3, -0.2]} scale={[1, 1, 1]} />
              </group>
            </group>
          </group>
          <group position={[-6.38, -3.54, 1.36]} rotation={[-1.22, 0, 2.8]} scale={[1, 1, 1]}>
            <group position={[0, 23.85, 0]} rotation={[-2.3, 0, -0.03]}>
              <group position={[0, 21.07, 0]} rotation={[1.36, -0.37, 0.04]}>
                <group position={[0, 11.1, 0]} rotation={[0.77, -0.29, 0.2]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[0.38, -1.61, -46.57]} rotation={[-1.25, -0.18, -0.04]} scale={[1, 1, 1]}>
          <group position={[0, 6.36, -0.7]} rotation={[0, 0.05, 0.07]}>
            <group position={[0, 7.47, 0]} rotation={[0.22, 0.11, 0.09]}>
              <group position={[0, 8.53, 0]} rotation={[0.22, 0.11, 0.09]}>
                <group position={[0, 9.6, 0]} rotation={[0.09, 0.01, -0.1]}>
                  <group position={[0, 11.12, 1.62]} rotation={[-0.55, 0, -0.19]} />
                </group>
                <group position={[4.68, 7.84, -0.19]} rotation={[1.63, -0.16, -1.7]} scale={[1, 1, 1]}>
                  <group position={[0, 9.88, 0]} rotation={[0.97, 0.29, -0.88]}>
                    <group position={[0, 12.7, 0]} rotation={[0.12, 0.17, 1.94]}>
                      <group position={[0, 16.55, 0]} rotation={[-0.35, 0.27, 0.25]} scale={[1, 1, 1]}>
                        <group position={[-2.45, 1.96, 0]} rotation={[0, 0.18, 0.45]}>
                          <group position={[-0.05, 2.51, 0]} rotation={[0.36, 0.03, -0.68]}>
                            <group position={[-0.56, 3.91, 0]} rotation={[0, 0, 0.33]} />
                          </group>
                        </group>
                        <group position={[0, 4.76, 0.05]} rotation={[0.84, 0.03, 0.3]}>
                          <group position={[0.03, 3.94, 0]} rotation={[1.73, 0.15, 0.31]} scale={[1, 1, 1]}>
                            <group position={[-0.01, 3.5, 0]} rotation={[0, 0, -0.01]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-4.68, 7.85, -0.2]} rotation={[1.62, 0.25, 1.35]}>
                  <group position={[0, 9.88, 0]} rotation={[0.83, 0.06, -1.01]} scale={[1, 1, 1]}>
                    <group position={[0, 12.7, 0]} rotation={[0.11, -0.14, -1.87]}>
                      <group position={[0, 16.57, 0]} rotation={[-0.04, -0.66, -0.31]}>
                        <group position={[2.28, 2.18, 0]} rotation={[0.09, -0.19, -0.41]}>
                          <group position={[0.04, 2.52, 0]} rotation={[0.07, -0.15, 0.55]} scale={[1, 1, 1]}>
                            <group position={[0.57, 3.95, 0]} rotation={[0, 0, -0.34]} scale={[1, 1, 1]} />
                          </group>
                        </group>
                        <group position={[0, 4.68, 0.16]} rotation={[1.13, -0.03, -0.22]} scale={[1, 1, 1]}>
                          <group position={[0.05, 3.63, 0]} rotation={[1.77, -0.24, -0.42]}>
                            <group position={[-0.15, 4.13, 0]} rotation={[0, 0, 0.08]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[6.38, -3.54, 1.07]} rotation={[-1.16, 0.14, -2.85]} scale={[1, 1, 1]}>
            <group position={[0, 23.9, 0]} rotation={[-2.35, 0.2, 0.02]}>
              <group position={[0, 21.07, 0]} rotation={[1.87, 0.41, 0.05]}>
                <group position={[0, 10.69, 0]} rotation={[0.75, 0.27, -0.2]} />
              </group>
            </group>
          </group>
          <group position={[-6.38, -3.54, 1.36]} rotation={[-0.44, -0.11, -2.98]} scale={[1, 1, 1]}>
            <group position={[0, 23.85, 0]} rotation={[-1.05, 0.17, -0.08]}>
              <group position={[0, 21.07, 0]} rotation={[1.79, -0.04, 0.13]} scale={[1, 1, 1]}>
                <group position={[0, 11.1, 0]} rotation={[0.92, -0.32, 0.2]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <group position={[0.33, -2.32, -49.33]} rotation={[-1.41, -0.09, -0.01]} scale={[1, 1, 1]}>
          <group position={[0, 6.36, -0.7]} rotation={[0.14, 0.21, -0.02]}>
            <group position={[0, 7.47, 0]} rotation={[-0.03, 0.03, 0.01]}>
              <group position={[0, 8.53, 0]} rotation={[-0.02, 0.03, 0.01]}>
                <group position={[0, 9.6, 0]} rotation={[0.32, -0.03, -0.04]}>
                  <group position={[0, 11.12, 1.62]} rotation={[-0.38, -0.11, 0.03]} />
                </group>
                <group position={[4.68, 7.84, -0.19]} rotation={[1.66, -0.34, -1.44]} scale={[1, 1, 1]}>
                  <group position={[0, 9.88, 0]} rotation={[0.83, 0.28, -0.84]}>
                    <group position={[0, 12.7, 0]} rotation={[0.11, 0.09, 1.25]} scale={[1, 1, 1]}>
                      <group position={[0, 16.55, 0]} rotation={[-0.05, -0.1, -0.18]} scale={[1, 1, 1]}>
                        <group position={[-2.45, 1.96, 0]} rotation={[0.24, 0.23, 0.43]}>
                          <group position={[-0.05, 2.51, 0]} rotation={[0.05, -0.01, -0.29]}>
                            <group position={[-0.56, 3.91, 0]} rotation={[-0.03, -0.01, 0.29]} />
                          </group>
                        </group>
                        <group position={[0, 4.76, 0.05]} rotation={[0.14, -0.01, 0.04]} scale={[1, 1, 1]}>
                          <group position={[0.03, 3.94, 0]} rotation={[0.24, 0, -0.01]} scale={[1, 1, 1]}>
                            <group position={[-0.01, 3.5, 0]} rotation={[0.04, 0, -0.01]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-4.68, 7.85, -0.2]} rotation={[1.61, 0.31, 1.51]}>
                  <group position={[0, 9.88, 0]} rotation={[0.75, 0.16, -0.36]}>
                    <group position={[0, 12.7, 0]} rotation={[0.11, -0.12, -1.51]}>
                      <group position={[0, 16.57, 0]} rotation={[-0.4, 0.04, 0]} scale={[1, 1, 1]}>
                        <group position={[2.28, 2.18, 0]} rotation={[0.18, -0.22, -0.35]}>
                          <group position={[0.04, 2.52, 0]} rotation={[0.02, -0.01, 0.32]}>
                            <group position={[0.57, 3.95, 0]} rotation={[-0.07, 0.01, -0.31]} />
                          </group>
                        </group>
                        <group position={[0, 4.68, 0.16]} rotation={[0.09, -0.02, -0.01]}>
                          <group position={[0.05, 3.63, 0]} rotation={[0.26, 0, -0.07]} scale={[1, 1, 1]}>
                            <group position={[-0.15, 4.13, 0]} rotation={[0.06, 0, 0.07]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[6.38, -3.54, 1.07]} rotation={[-0.86, 0.01, -2.9]} scale={[1, 1, 1]}>
            <group position={[0, 23.9, 0]} rotation={[-2.27, -0.04, -0.04]}>
              <group position={[0, 21.07, 0]} rotation={[0.86, 0.16, -0.21]}>
                <group position={[0, 10.69, 0]} rotation={[0.65, 0.25, -0.21]} />
              </group>
            </group>
          </group>
          <group position={[-6.38, -3.54, 1.36]} rotation={[-0.13, -0.02, -3.07]}>
            <group position={[0, 23.85, 0]} rotation={[-0.85, -0.04, -0.06]}>
              <group position={[0, 21.07, 0]} rotation={[1.58, -0.28, 0.18]}>
                <group position={[0, 11.1, 0]} rotation={[1.14, -0.36, 0.2]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
